module.exports = {
    apps: [
        {
            name: 'auth-manager',
            script: './dist/apps/auth-manager/main.js',
            instances: 1,
            exec_mode: 'cluster',
            env: {
                NODE_ENV: 'production',
                PORT: 3001,
            },
            error_file: './logs/auth-manager-error.log',
            out_file: './logs/auth-manager-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            max_memory_restart: '500M',
            autorestart: true,
            watch: false,
            max_restarts: 10,
            min_uptime: '10s',
        },
        {
            name: 'manage-employees',
            script: './dist/apps/manage-employees/main.js',
            instances: 2,
            exec_mode: 'cluster',
            env: {
                NODE_ENV: 'production',
                PORT: 3002,
            },
            error_file: './logs/manage-employees-error.log',
            out_file: './logs/manage-employees-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            max_memory_restart: '800M',
            autorestart: true,
            watch: false,
            max_restarts: 10,
            min_uptime: '10s',
        },
        {
            name: 'api-gateway',
            script: './dist/apps/api-gateway/main.js',
            instances: 'max', // Utilise tous les CPU disponibles
            exec_mode: 'cluster',
            env: {
                NODE_ENV: 'production',
                PORT: 3000,
            },
            error_file: './logs/api-gateway-error.log',
            out_file: './logs/api-gateway-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            merge_logs: true,
            max_memory_restart: '1G',
            autorestart: true,
            watch: false,
            max_restarts: 10,
            min_uptime: '10s',
        },
    ],
};