-- MySQL Script generated by MySQL Workbench
-- Thu Dec 18 21:14:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auth_manager_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auth_manager_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auth_manager_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `auth_manager_db` ;

-- -----------------------------------------------------
-- Table `auth_manager_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`credentials` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` VARCHAR(36) NOT NULL,
  `type` ENUM('password', 'ldap', 'api_key') NOT NULL DEFAULT 'password',
  `identifier` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `last_login_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_credentials_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `user_identifier_UNIQUE` (`user_id` ASC, `identifier` ASC) VISIBLE,
  CONSTRAINT `fk_credentials_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`roles` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`permissions` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `resource` VARCHAR(255) NULL,
  `action` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`roles_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`roles_permissions` (
  `role_id` VARCHAR(36) NOT NULL,
  `permission_id` VARCHAR(36) NOT NULL,
  INDEX `fk_roles_permissions_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_roles_permissions_permissions1_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_permissions_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_roles_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `auth_manager_db`.`permissions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`users_roles` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_users_roles_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_roles_roles1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`users_roles` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_users_roles_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_roles_roles1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`roles_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`roles_permissions` (
  `role_id` VARCHAR(36) NOT NULL,
  `permission_id` VARCHAR(36) NOT NULL,
  INDEX `fk_roles_permissions_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_roles_permissions_permissions1_idx` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_permissions_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_roles_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `auth_manager_db`.`permissions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`refresh_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`refresh_tokens` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `token` VARCHAR(512) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` DATETIME NOT NULL,
  `is_revoked` TINYINT NOT NULL DEFAULT 0,
  `device_info` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_refresh_tokens_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `idx_expires_at` (`expires_at` ASC) VISIBLE,
  CONSTRAINT `fk_refresh_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
