-- MySQL Script generated by MySQL Workbench
-- Mon Dec  8 13:02:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auth_manager_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auth_manager_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auth_manager_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `auth_manager_db` ;

-- -----------------------------------------------------
-- Table `auth_manager_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `credential_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_credentials_idx` (`credential_id` ASC),
  CONSTRAINT `fk_users_credentials`
    FOREIGN KEY (`credential_id`)
    REFERENCES `auth_manager_db`.`credentials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`credentials` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `last_login_at` DATETIME NULL,
  `user_id` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_credentials_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_credentials_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`roles` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `auth_manager_db`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`permissions` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `resource` VARCHAR(255) NULL,
  `action` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `auth_manager_db`.`roles_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`roles_permissions` (
  `id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  `permission_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_roles_permissions_roles1_idx` (`role_id` ASC),
  INDEX `fk_roles_permissions_permissions1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_roles_permissions_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `auth_manager_db`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`users_roles` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_users_roles_users1_idx` (`user_id` ASC),
  INDEX `fk_users_roles_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`users_roles` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_users_roles_users1_idx` (`user_id` ASC),
  INDEX `fk_users_roles_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_manager_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `auth_manager_db`.`roles_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_manager_db`.`roles_permissions` (
  `id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  `permission_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_roles_permissions_roles1_idx` (`role_id` ASC),
  INDEX `fk_roles_permissions_permissions1_idx` (`permission_id` ASC),
  CONSTRAINT `fk_roles_permissions_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_manager_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_permissions_permissions1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `auth_manager_db`.`permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
