-- MySQL Script generated by MySQL Workbench
-- Fri May 30 15:45:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema employees_management_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employees_management_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees_management_db` DEFAULT CHARACTER SET utf8 ;
USE `employees_management_db` ;

-- -----------------------------------------------------
-- Table `employees_management_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('admin', 'manager', 'hr') NOT NULL,
  `is_active` TINYINT NOT NULL,
  `last_login_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `employees_management_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `manager_id` INT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departments_users_idx` (`manager_id` ASC),
  INDEX `fk_departments_departments1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_department_user`
    FOREIGN KEY (`manager_id`)
    REFERENCES `employees_management_db`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_department_department`
    FOREIGN KEY (`parent_id`)
    REFERENCES `employees_management_db`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`positions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `title` VARCHAR(100) NOT NULL,
  `level` VARCHAR(50) NULL,
  `salary_range_min` DECIMAL(16,2) NULL,
  `salary_range_max` DECIMAL(16,2) NULL,
  `description` TEXT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_positions_departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_position_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `employees_management_db`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(50) NULL,
  `address` TEXT NULL,
  `hire_date` DATE NOT NULL,
  `birth_date` DATE NULL,
  `gender` ENUM('male', 'female', 'other') NULL,
  `marital_status` ENUM('single', 'married', 'divorced', 'widowed') NULL,
  `salary` DECIMAL(16,2) NULL,
  `emergency_contact_name` VARCHAR(200) NULL,
  `emergency_contact_phone` VARCHAR(50) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  `position_id` INT NOT NULL,
  `department_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_employees_positions1_idx` (`position_id` ASC),
  INDEX `fk_employees_departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employee_position`
    FOREIGN KEY (`position_id`)
    REFERENCES `employees_management_db`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `employees_management_db`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`leave_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`leave_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `max_days` INT NOT NULL,
  `is_paid` TINYINT NOT NULL DEFAULT 1,
  `requires_approval` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `employees_management_db`.`leave_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`leave_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `reason` TEXT NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'cancelled') NOT NULL DEFAULT 'pending',
  `approved_at` DATETIME NULL,
  `rejection_reason` TEXT NULL,
  `employee_id` INT NOT NULL,
  `leave_type_id` INT NOT NULL,
  `approved_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leave_request_employee_idx` (`employee_id` ASC),
  INDEX `fk_leave_request_leave_type_idx` (`leave_type_id` ASC),
  INDEX `fk_leave_request_user_idx` (`approved_by` ASC),
  INDEX `leave_dates_idx` (`start_date` ASC, `end_date` ASC),
  CONSTRAINT `fk_leave_request_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employees_management_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leave_request_leave_type`
    FOREIGN KEY (`leave_type_id`)
    REFERENCES `employees_management_db`.`leave_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leave_request_user`
    FOREIGN KEY (`approved_by`)
    REFERENCES `employees_management_db`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`attendances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`attendances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `date` DATE NOT NULL,
  `check_in` TIME NULL,
  `check_out` TIME NULL,
  `status` ENUM('present', 'absent', 'late', 'half_day', 'on_leave') NOT NULL,
  `notes` TEXT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendances_employees1_idx` (`employee_id` ASC),
  UNIQUE INDEX `employee_date_UNIQUE` (`employee_id` ASC, `date` ASC),
  CONSTRAINT `fk_attendance_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employees_management_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `category` VARCHAR(100) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `employees_management_db`.`employees_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`employees_skills` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `proficiency_level` ENUM('beginner', 'intermediate', 'advanced', 'expert') NULL,
  `years_of_experience` INT NULL,
  `skill_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_skills_skills1_idx` (`skill_id` ASC),
  INDEX `fk_employees_skills_employees1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_employee_skill_skill`
    FOREIGN KEY (`skill_id`)
    REFERENCES `employees_management_db`.`skills` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_skill_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employees_management_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `document_type` VARCHAR(100) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `file_hash` VARCHAR(64) NULL,
  `file_size` BIGINT NOT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  `employee_id` INT NOT NULL,
  `uploaded_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_document_employee_idx` (`employee_id` ASC),
  INDEX `fk_document_user_idx` (`uploaded_by` ASC),
  CONSTRAINT `fk_document_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employees_management_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_user`
    FOREIGN KEY (`uploaded_by`)
    REFERENCES `employees_management_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `is_read` TINYINT NOT NULL DEFAULT 0,
  `type` VARCHAR(50) NOT NULL,
  `related_entity_type` VARCHAR(50) NULL,
  `related_entity_id` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notification_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `employees_management_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_management_db`.`leave_balances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_management_db`.`leave_balances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `deleted` DATETIME NULL,
  `year` INT NOT NULL,
  `days_available` DECIMAL(5,2) NOT NULL,
  `days_taken` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `leave_type_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leave_balance_leave_type_idx` (`leave_type_id` ASC),
  INDEX `fk_leave_balance_employee_idx` (`employee_id` ASC),
  UNIQUE INDEX `employee_leave_type_year_UNIQUE` (`employee_id` ASC, `leave_type_id` ASC, `year` ASC),
  CONSTRAINT `fk_leave_balances_leave_types1`
    FOREIGN KEY (`leave_type_id`)
    REFERENCES `employees_management_db`.`leave_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leave_balances_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employees_management_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
