-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 00:08:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema employees_manager_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employees_manager_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees_manager_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `employees_manager_db` ;

-- -----------------------------------------------------
-- Table `employees_manager_db`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_manager_db`.`departments` ;

CREATE TABLE IF NOT EXISTS `employees_manager_db`.`departments` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `status` ENUM('active', 'inactive', 'archived') NOT NULL DEFAULT 'active',
  `location` VARCHAR(255) NULL,
  `budget` DECIMAL(15,2) NULL,
  `parent_id` VARCHAR(36) NULL,
  `manager_id` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_departments_departments1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_departments_employees1_idx` (`manager_id` ASC) INVISIBLE,
  INDEX `status_departments_idx` (`status` ASC) INVISIBLE,
  INDEX `delete_at_departments_idx` (`deleted_at` ASC) VISIBLE,
  CONSTRAINT `fk_departments_departments1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `employees_manager_db`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_employees1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `employees_manager_db`.`employees` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `employees_manager_db`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employees_manager_db`.`employees` ;

CREATE TABLE IF NOT EXISTS `employees_manager_db`.`employees` (
  `id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `user_id` VARCHAR(255) NULL,
  `employee_code` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone_number` VARCHAR(20) NULL,
  `hire_date` DATE NOT NULL,
  `birth_date` DATE NULL,
  `position` VARCHAR(100) NULL,
  `salary` DECIMAL(12,2) NULL DEFAULT 0,
  `status` ENUM('active', 'on_leave', 'suspended', 'terminated') NOT NULL DEFAULT 'active',
  `address` TEXT NULL,
  `city` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `department_id` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `employee_code_UNIQUE` (`employee_code` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) INVISIBLE,
  INDEX `status_employees_idx` (`status` ASC) INVISIBLE,
  INDEX `deleted_at_employees_idx` (`deleted_at` ASC) VISIBLE,
  INDEX `fk_employees_departments_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_departments`
    FOREIGN KEY (`department_id`)
    REFERENCES `employees_manager_db`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
